package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"app/internal/core/graph/model"
	"context"
)

// CreateFriendship is the resolver for the createFriendship field.
func (r *mutationResolver) CreateFriendship(ctx context.Context, input model.CreateFriendshipInput) (*model.Friendship, error) {
	return r.FriendshipsMod.API.CreateFriendship(ctx, input)
}

// AcceptFriendshipRequest is the resolver for the acceptFriendshipRequest field.
func (r *mutationResolver) AcceptFriendshipRequest(ctx context.Context, input model.AcceptFriendshipInput) (*model.Friendship, error) {
	//panic(fmt.Errorf("not implemented: AcceptFriendshipRequest - acceptFriendshipRequest"))
	return r.FriendshipsMod.API.AcceptFriendshipRequest(ctx, input)
}

// RemoveFriendship is the resolver for the removeFriendshipRequest field.
func (r *mutationResolver) RemoveFriendship(ctx context.Context, input model.RemoveFriendshipInput) (bool, error) {
	return r.FriendshipsMod.API.RemoveFriendship(ctx, input)
}

// MyFriends is the resolver for the myFriends field.
func (r *queryResolver) MyFriends(ctx context.Context, status *model.FriendshipStatus) (*model.PaginatedFriendshipList, error) {
	return r.FriendshipsMod.API.MyFriends(ctx, status)
}

// FriendshipList is the resolver for the friendshipRequestList field.
func (r *queryResolver) FriendshipList(ctx context.Context, filter *model.FriendshipFilter) (*model.PaginatedFriendshipList, error) {
	return r.FriendshipsMod.API.FriendshipList(ctx, filter)
}
