package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"app/internal/core/graph/model"
	"context"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.UserInput) (*model.User, error) {
	return r.UsersMod.API.CreateUser(ctx, input)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UserInput) (*model.User, error) {
	return r.UsersMod.API.UpdateUser(ctx, id, &input)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, filter *model.DefaultFilterInput) (*model.PaginatedUserList, error) {
	return r.UsersMod.API.Users(ctx, filter)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	return r.UsersMod.API.FindOneUser(ctx, id)
}

// Me is the resolver for me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return r.UsersMod.API.Me(ctx)
}
